# docker-compose.yml
version: "3.9"

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    web:
        build: app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        # directorios para el archivo de configuración y archivos del static
        volumes:
            - ./conf:/etc/nginx/conf.d
            - ./web/static:/var/www/static 
        depends_on:
            - web